practice/practice/practice/Models/Course.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace practice.Models
{
    public class Course
    {
        [Key]
        public int CourseID { get; set; }


        public string Description { get; set; }


        

        public virtual ICollection<Student> Students { get; set; }
    }
}

practice/practice/practice/Models/PracticeCMSContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;


namespace practice.Models
{
    public class PracticeCMSContext : DbContext
    {
            public PracticeCMSContext()
            {

            }
            public DbSet<Student> Students { get; set; }
            public DbSet<Course> Courses { get; set; }

        
    }
}

practice/practice/practice/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace practice.Models
{
    public class Student
    {
        
        [Key]
        public int StudentID { get; set; }
        public string S_Name { get; set; }
        public string S_Email { get; set; }
        
        public Course Course { get; set; }


    }

}
    

practice/practice/practice/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using practice.Models;
using System.Diagnostics;
using System.Data.SqlClient;
using System.IO;

namespace practice.Controllers
{
    

    public class CourseController : Controller
    {
        private PracticeCMSContext db = new PracticeCMSContext();
        // GET: Course
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List()
        {

            return View(db.Courses.ToList());
        }

        public ActionResult New()
        {
            //no information needed from db

            return View();
        }
    }
}

practice/practice/practice/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace practice.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

practice/practice/practice/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using practice.Models;
using System.Diagnostics;
using System.Data.SqlClient;
using System.IO;


namespace practice.Controllers
{

    public class StudentController : Controller
    {
        private PracticeCMSContext db = new PracticeCMSContext();
        // GET: Student
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List()
        {

            return View(db.Students.ToList());
        }

        public ActionResult New()
        {
            //no information needed from db

            return View();
        }
        // Create new student

        [HttpPost]
        public ActionResult Create(string S_Name, string S_Email)
        {
            //actually ask to put info into db

            string query = "insert into students (S_Name, S_Email) values (@S_Name, @S_Email )";
            SqlParameter[] myparams = new SqlParameter[2];
            myparams[0] = new SqlParameter("@S_Name", S_Name);
            myparams[1] = new SqlParameter("@S_Email", S_Email);


            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("List");

        }
        // GET: Student/Edit/5
        public ActionResult Edit(int? id)
        {
            Debug.WriteLine("testing student edit");
            if ((id == null) || (db.Students.Find(id) == null))
            {
                return HttpNotFound();
            }
            string query = "select * from students where StudentID=@id";
            SqlParameter param = new SqlParameter("@id", id);
            Student mystudent = db.Students.SqlQuery(query, param).FirstOrDefault();
            return View(mystudent);
        }

        
        // POST: Students/Edit/5

        [HttpPost]

        public ActionResult Edit(int id, string S_Name, string S_Email)
        {

            if ((id == null) || (db.Students.Find(id)) == null)
            {
                return HttpNotFound();
            }

            string query = "update students set S_Name=@S_Name, S_Email=@S_Email  where StudentID = @id";
            SqlParameter[] myparams = new SqlParameter[3];
            myparams[0] = new SqlParameter("@id", id);
            myparams[1] = new SqlParameter("@S_Name", S_Name);
            myparams[2] = new SqlParameter("@S_Email", S_Email);
           
            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("List");
        }
        //delete Student
        // GET: Students/Delete


        public ActionResult Delete(int? id)
        {
            if ((id == null) || (db.Students.Find(id) == null))
            {
                return HttpNotFound();
            }
            string query = "delete from Students where StudentID=@id";
            SqlParameter param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);
            return RedirectToAction("List");

        }

    }
}

practice/practice/practice/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

practice/practice/practice/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

practice/practice/practice/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

practice/practice/practice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.My School</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("School", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Students", "List", "Student")</li>
                    <li>@Html.ActionLink("Courses", "List", "Course")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

practice/practice/practice/Views/Student/Delete.cshtml
@model practice.Models.Student
@{
                /**/

                ViewBag.Title = "Delete";
}



<h2>Delete</h2>
<h3> Are you sure?</h3>
<h4>  </h4>
<hr />
<d1 class="d1-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.S_Name)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.S_Name)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.S_Email)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.S_Email)
    </dd>


</d1>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        @Html.ActionLink("Back to List", "List")

    </div>
}

practice/practice/practice/Views/Student/Edit.cshtml
@model practice.Models.Student
@{
    ViewBag.Title = "Edit";
}


<h2>Edit Driver</h2>

<form method="POST" action="/Driver/Edit/@Model.StudentID">
    <div>
        <label>Name</label>
        <input type="text" value="@Model.S_Name" name="S_Name" />
    </div>
    <div>
        <label>Email</label>
        <input type="text" value="@Model.S_Email" name="S_Email" />
    </div>
    

    <div>
        <input type="submit" value="Submit" />
    </div>
</form>



<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

practice/practice/practice/Views/Student/List.cshtml
@model IEnumerable<practice.Models.Student>
@{
    ViewBag.Title = "List";
}


<div class="banner" id="studentbanner">

</div>
<h2>List of Students</h2>


<div class="recadd">
    @Html.ActionLink("New Student", "New", "Student")
</div>

<table id="TableHeader" class="table">
    <tr>
        <th>Name</th>
        <th>Email</th>
    </tr>
    @foreach (var item in Model)

    {
        <tr>

            <td>@item.S_Name</td>
            <td>@item.S_Email</td>
            
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.StudentID }) |
                @Html.ActionLink("Details", "Details", new { id = item.StudentID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.StudentID })
            </td>
        </tr>
    }
</table>

practice/practice/practice/Views/Student/New.cshtml
@model practice.Models.Student
    @{
        ViewBag.Title = "New";
    }

    <h2>New Student</h2>

        <form id="myform" action="/Student/Create" method="POST">
        <div class="inputrow">
            <label class="inputlabel"> Student ID</label>
            <input type="text" name="StudentID" />
        </div>
        <div class="inputrow">
            <label class="inputlabel"> Name</label>
            <input type="text" name="S_Name" />
        </div>

        <div class="inputrow">
            <label class="inputlabel"> Email </label>
            <input type="text" name="S_Email" />
        </div>
        <div class="inputrow">
            <input type="submit" value="Submit" />
        </div>
    </form>

    <br />

    <div>
        @Html.ActionLink("Back to List", "List")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }